name: Generate uv.lock report

on:
  pull_request:
    paths:
      - 'uv.lock'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: mw-root/uv-lock-report@v0.13.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
